### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by jhoughjr** [the-road-to-react-with-firebase/react-firestore-authentication#9]
Great boilerplate and tutorial. 
I feel like I read the solution to this earlier but can't find the issue.
Firebase.js is crashing 
Uncaught (in promise) TypeError: Cannot read property 'roles' of undefined
 in Firebase.js line 76.
It's where it tries to set default roles, but it appears the snapshot.data is null for some reason.
I hope to get this working since we are considering using it and purchasing a team license.

**Comment by jhoughjr** [comment]
It appears as if the code that should populate a users collection from auth users on creation isn't happening. I don't see a users collection in the console.
I didn't see any errors indicating that though.

**Comment by jhoughjr** [comment]
It appears to be addressed in PR#4. Investigating.

**Comment by jhoughjr** [comment]
I can confirm the changes from PR#4 fixes the crash. I'll keep an eye out for any brewing changes that may have introduced.

**Comment by rwieruch** [comment]
Thanks for your thoughts @jhoughjr 

I though PR#4 removes roles entirely, because it always sets the roles array to empty. Not sure whether this is the correct behavior. 

Can you try to remove your user in the Firebase project's dashboard from the authentication database and your normal database? Then register the user again, with or without role, and see if it works.

**Comment by jhoughjr** [comment]
Yeah, I'll try that as currently I'm hardcoding to admin for everyone.
(one area where swift optionals would help I think.)

**Comment by rwieruch** [comment]
Did the recent version work out for you @jhoughjr ?

**Comment by fredrivett** [comment]
@rwieruch Sorry for jumping into this late. PR#4 sets `roles` to an empty array by default, but because `...dbUser` is spread at the end, if `dbUser` has any roles then the array will be overwritten with whatever `dbUser.roles` has.

It fixed the issue for me, but I didn't spend too long on it and have only had a couple hours using `react-firestore-authentication`, so I'm not best placed to know if this fix is desired for all outcomes.

Seems logical to me and to confirm it won't remove roles, but simply set an elegant default even in cases where `dbUser` returns `undefined`.

**Comment by rwieruch** [comment]
Thanks for getting back to us @fredrivett I will mark this as solved for now :)

**Comment by GoeranEnvirio** [comment]
It doesn't seem to be fixed. I just got this error.
